//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTrungTamNN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public int AttendanceID { get; set; }
        public int EnrollmentID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual ENROLLMENT ENROLLMENT { get; set; }
    }
}
