//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTrungTamNN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int FeedbackID { get; set; }
        public int EnrollmentID { get; set; }
        public int TeacherID { get; set; }
        public string Comments { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ENROLLMENT ENROLLMENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
